#THIS FILE IS TO CHANGE THE UB_CLASSES.CSV FILE INTO SOMETHING THAT THE DATABASE CAN USE 
#REMOVE THE UNUSABLE DATES, SPLIT INTO A START AND END DATE AND REMOVE AN EXTRA SPACE WHEN SPLITING 
#THE IRR:

#CERTAIN CLASSES HAVE MORE THAN 1 MEETING PLACE
#CERTAIN PLACES LOCATIONS ARE ARR
#DATES ARE TBA
#ROOM OR DATES COMPLETELY EMPTY
#1 DATE OR LOCATION SHOWN BUT NOT THE OTHER
#HIGHER PRIORITY WHEN LOCATION IS REMOTE (COMPLETELY REMOVE FROM LIST)

#summary 
#ROOM CAN BE : COMPLETELY EMPTY, REMOTE, 2 FIELDS, ARR, TBA
#OR
#DATE CAN BE : COMPLETELY EMPTY, REMOTE, 2 FIELDS, ARR, TBA
#THINGS THAT CAN STILL BE SOLVED ARE THE 2 FIELDS SITUATION 
#COMPLETELY REMOVE ANY FIELD WHICH HAS :
#EMPTY IN ONE OF THEM
#REMOTE IN ONE OF THEM 
#ARR IN ONE OF THEM
#TBA IN ONE OF THEM
#time : multiple meeting patterns
#room c

#iterate through the file first to remove the unfixables
#iterate again to fix the fixable
#split the 2 dates
#remove first fields space
#put into database in a seperate file
import csv 
#GOOD DAYS DONT HAVE "TBA, EMPTY"
#GOOD TIMES HAVE REGEX "AM/PM TO AM/PM"
#GOOD ROOOMS DONT HAVE "REMOTE/ ARR/SEE CLASS DETAIL/EMPTY/MAI??/ ROOM HAS 2??/FUTURE TERM CSS/SQUIRE 99999?/ON CAMPUS- TBD (CSS)
# OFF CA 00/TO BE DETERMINED/OFF CAMPUS-OVERSEAS/TO BE DETERMINED(HEALTHSCI)"
#GOOD CAMPUSES HAVE NORTH/SOUTH OR DOWNTOWN

rooms = []
with open("ub_classes.csv","w") as f:
    with open("ub_classes_flawed.csv", "r") as p:
        reader = csv.reader(p)
        writer = csv.writer(f)
        for line in reader:
            if line[7] not in rooms:
                rooms.append(line[7])
        for room in rooms:
            print(room)